-- =================================================================
-- ENUM 타입 선언 (PostgreSQL 방식)
-- =================================================================
CREATE TYPE difficulty_level AS ENUM ('입문', '초급', '중급', '고급');
CREATE TYPE enrollment_status AS ENUM ('수강전', '수강중', '완강');


-- =================================================================
-- Class 및 관련 테이블
-- =================================================================
CREATE TABLE "Class" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    thumbnail_url TEXT,
    difficulty difficulty_level NOT NULL,
    total_lecture_count INT NOT NULL DEFAULT 0,
    total_duration_secs INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
COMMENT ON TABLE "Class" IS '전체 클래스';

-- 클래스의 'updated_at'을 자동으로 갱신하는 트리거 함수
CREATE OR REPLACE FUNCTION trigger_set_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_class_timestamp
BEFORE UPDATE ON "Class"
FOR EACH ROW
EXECUTE FUNCTION trigger_set_timestamp();


CREATE TABLE "ClassLearningGoal" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id BIGINT NOT NULL REFERENCES "Class"(id) ON DELETE CASCADE,
    content TEXT NOT NULL
);
COMMENT ON TABLE "ClassLearningGoal" IS '클래스의 학습 목표';


CREATE TABLE "BackgroundKnowledge" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id BIGINT NOT NULL REFERENCES "Class"(id) ON DELETE CASCADE,
    content TEXT NOT NULL
);
COMMENT ON TABLE "BackgroundKnowledge" IS '필요한 배경 지식';


-- =================================================================
-- Module & Lecture 테이블
-- =================================================================
CREATE TABLE "Module" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id BIGINT NOT NULL REFERENCES "Class"(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    sequence INT NOT NULL,
    UNIQUE (class_id, sequence)
);
COMMENT ON TABLE "Module" IS '클래스 내 강의 묶음 단위 (챕터)';


CREATE TABLE "Lecture" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 반정규화: 조회 성능을 위해 class_id 추가
    class_id BIGINT NOT NULL REFERENCES "Class"(id) ON DELETE CASCADE,
    module_id BIGINT NOT NULL REFERENCES "Module"(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    sequence INT NOT NULL,
    video_url TEXT,
    duration_secs INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (module_id, sequence)
);
COMMENT ON TABLE "Lecture" IS '개별 동영상 강의';

-- Lecture의 'updated_at'을 자동으로 갱신하는 트리거
CREATE TRIGGER set_lecture_timestamp
BEFORE UPDATE ON "Lecture"
FOR EACH ROW
EXECUTE FUNCTION trigger_set_timestamp();


CREATE TABLE "LectureKeypoint" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lecture_id BIGINT NOT NULL REFERENCES "Lecture"(id) ON DELETE CASCADE,
    content TEXT NOT NULL
);
COMMENT ON TABLE "LectureKeypoint" IS '강의의 주요 내용';


CREATE TABLE "LectureMaterial" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lecture_id BIGINT NOT NULL REFERENCES "Lecture"(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    file_url TEXT NOT NULL
);
COMMENT ON TABLE "LectureMaterial" IS '강의별 학습 자료';


-- =================================================================
-- User(profiles) 와의 관계 테이블
-- =================================================================
CREATE TABLE "Enrollment" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    class_id BIGINT NOT NULL REFERENCES "Class"(id) ON DELETE CASCADE,
    status enrollment_status NOT NULL DEFAULT '수강전',
    -- 반정규화: 클래스 진행률 계산을 위해 추가
    completed_lecture_count INT NOT NULL DEFAULT 0,
    last_viewed_lecture_id BIGINT REFERENCES "Lecture"(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (user_id, class_id)
);
COMMENT ON TABLE "Enrollment" IS '수강 신청 정보 및 클래스 단위 진행률';

-- Enrollment의 'updated_at'을 자동으로 갱신하는 트리거
CREATE TRIGGER set_enrollment_timestamp
BEFORE UPDATE ON "Enrollment"
FOR EACH ROW
EXECUTE FUNCTION trigger_set_timestamp();


CREATE TABLE "LectureProgress" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    lecture_id BIGINT NOT NULL REFERENCES "Lecture"(id) ON DELETE CASCADE,
    progress_secs INT NOT NULL DEFAULT 0,
    is_completed BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (user_id, lecture_id)
);
COMMENT ON TABLE "LectureProgress" IS '강의별 학습 진도';

-- LectureProgress의 'updated_at'을 자동으로 갱신하는 트리거
CREATE TRIGGER set_lecture_progress_timestamp
BEFORE UPDATE ON "LectureProgress"
FOR EACH ROW
EXECUTE FUNCTION trigger_set_timestamp();


CREATE TABLE "ClassInstructor" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id BIGINT NOT NULL REFERENCES "Class"(id) ON DELETE CASCADE,
    instructor_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    role_title TEXT,
    intro_message TEXT,
    UNIQUE (class_id, instructor_id)
);
COMMENT ON TABLE "ClassInstructor" IS '클래스-강사 연결 정보';


-- =================================================================
-- 기타 관계 테이블
-- =================================================================
CREATE TABLE "RelatedClass" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_a_id BIGINT NOT NULL REFERENCES "Class"(id) ON DELETE CASCADE,
    class_b_id BIGINT NOT NULL REFERENCES "Class"(id) ON DELETE CASCADE,
    UNIQUE (class_a_id, class_b_id),
    CHECK (class_a_id < class_b_id)
);
COMMENT ON TABLE "RelatedClass" IS '관련 Class 관계';
